
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'LoaderOverlay': typeof import("../../src/presentation/components/ui/LoaderOverlay.vue").default
  'UIOverlay': typeof import("../../src/presentation/components/ui/UIOverlay.vue").default
  'BleedingText': typeof import("../../src/components/BleedingText.vue").default
  'CustomCursor': typeof import("../../src/components/CustomCursor.vue").default
  'PoemMiniature': typeof import("../../src/components/PoemMiniature.vue").default
  'GalleryScene': typeof import("../../src/components/canvas/GalleryScene.vue").default
  'LiquidText': typeof import("../../src/components/canvas/LiquidText.vue").default
  'LoadingSpiral': typeof import("../../src/components/canvas/LoadingSpiral.vue").default
  'MainScene': typeof import("../../src/components/canvas/MainScene.vue").default
  'PoemCard': typeof import("../../src/components/canvas/PoemCard.vue").default
  'PostProcessing': typeof import("../../src/components/canvas/PostProcessing.vue").default
  'SineWaveMesh': typeof import("../../src/components/canvas/SineWaveMesh.vue").default
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'Align': typeof import("@tresjs/cientos").Align
  'AnimatedSprite': typeof import("@tresjs/cientos").AnimatedSprite
  'Backdrop': typeof import("@tresjs/cientos").Backdrop
  'BakeShadows': typeof import("@tresjs/cientos").BakeShadows
  'BaseCameraControls': typeof import("@tresjs/cientos").BaseCameraControls
  'Billboard': typeof import("@tresjs/cientos").Billboard
  'Box': typeof import("@tresjs/cientos").Box
  'CameraControls': typeof import("@tresjs/cientos").CameraControls
  'CatmullRomCurve3': typeof import("@tresjs/cientos").CatmullRomCurve3
  'Circle': typeof import("@tresjs/cientos").Circle
  'Cone': typeof import("@tresjs/cientos").Cone
  'ContactShadows': typeof import("@tresjs/cientos").ContactShadows
  'CubeCamera': typeof import("@tresjs/cientos").CubeCamera
  'CustomShaderMaterial': typeof import("@tresjs/cientos").CustomShaderMaterial
  'Cylinder': typeof import("@tresjs/cientos").Cylinder
  'Dodecahedron': typeof import("@tresjs/cientos").Dodecahedron
  'Edges': typeof import("@tresjs/cientos").Edges
  'Environment': typeof import("@tresjs/cientos").Environment
  'FBXModel': typeof import("@tresjs/cientos").FBXModel
  'Fbo': typeof import("@tresjs/cientos").Fbo
  'Fit': typeof import("@tresjs/cientos").Fit
  'GLTFModel': typeof import("@tresjs/cientos").GLTFModel
  'GlobalAudio': typeof import("@tresjs/cientos").GlobalAudio
  'GradientTexture': typeof import("@tresjs/cientos").GradientTexture
  'Grid': typeof import("@tresjs/cientos").Grid
  'HolographicMaterial': typeof import("@tresjs/cientos").HolographicMaterial
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html
  'Icosahedron': typeof import("@tresjs/cientos").Icosahedron
  'Image': typeof import("@tresjs/cientos").Image
  'KeyboardControls': typeof import("@tresjs/cientos").KeyboardControls
  'Lensflare': typeof import("@tresjs/cientos").Lensflare
  'Levioso': typeof import("@tresjs/cientos").Levioso
  'Lightformer': typeof import("@tresjs/cientos").Lightformer
  'Line2': typeof import("@tresjs/cientos").Line2
  'MapControls': typeof import("@tresjs/cientos").MapControls
  'Mask': typeof import("@tresjs/cientos").Mask
  'MeshDiscardMaterial': typeof import("@tresjs/cientos").MeshDiscardMaterial
  'MeshGlassMaterial': typeof import("@tresjs/cientos").MeshGlassMaterial
  'MeshReflectionMaterial': typeof import("@tresjs/cientos").MeshReflectionMaterial
  'MeshWobbleMaterial': typeof import("@tresjs/cientos").MeshWobbleMaterial
  'MouseParallax': typeof import("@tresjs/cientos").MouseParallax
  'Ocean': typeof import("@tresjs/cientos").Ocean
  'Octahedron': typeof import("@tresjs/cientos").Octahedron
  'OrbitControls': typeof import("@tresjs/cientos").OrbitControls
  'Outline': typeof import("@tresjs/cientos").Outline
  'Plane': typeof import("@tresjs/cientos").Plane
  'PointerLockControls': typeof import("@tresjs/cientos").PointerLockControls
  'PositionalAudio': typeof import("@tresjs/cientos").PositionalAudio
  'Precipitation': typeof import("@tresjs/cientos").Precipitation
  'Reflector': typeof import("@tresjs/cientos").Reflector
  'Ring': typeof import("@tresjs/cientos").Ring
  'RoundedBox': typeof import("@tresjs/cientos").RoundedBox
  'SVG': typeof import("@tresjs/cientos").SVG
  'Sampler': typeof import("@tresjs/cientos").Sampler
  'ScreenSizer': typeof import("@tresjs/cientos").ScreenSizer
  'ScreenSpace': typeof import("@tresjs/cientos").ScreenSpace
  'ScrollControls': typeof import("@tresjs/cientos").ScrollControls
  'Sky': typeof import("@tresjs/cientos").Sky
  'Smoke': typeof import("@tresjs/cientos").Smoke
  'SoftShadows': typeof import("@tresjs/cientos").SoftShadows
  'Sparkles': typeof import("@tresjs/cientos").Sparkles
  'Sphere': typeof import("@tresjs/cientos").Sphere
  'Stars': typeof import("@tresjs/cientos").Stars
  'Stats': typeof import("@tresjs/cientos").Stats
  'StatsGl': typeof import("@tresjs/cientos").StatsGl
  'Superformula': typeof import("@tresjs/cientos").Superformula
  'Tetrahedron': typeof import("@tresjs/cientos").Tetrahedron
  'Text3D': typeof import("@tresjs/cientos").Text3D
  'Torus': typeof import("@tresjs/cientos").Torus
  'TorusKnot': typeof import("@tresjs/cientos").TorusKnot
  'TransformControls': typeof import("@tresjs/cientos").TransformControls
  'Tube': typeof import("@tresjs/cientos").Tube
  'ASCIIPmndrs': typeof import("@tresjs/post-processing").ASCIIPmndrs
  'BarrelBlurPmndrs': typeof import("@tresjs/post-processing").BarrelBlurPmndrs
  'BloomPmndrs': typeof import("@tresjs/post-processing").BloomPmndrs
  'BrightnessContrastPmndrs': typeof import("@tresjs/post-processing").BrightnessContrastPmndrs
  'ChromaticAberrationPmndrs': typeof import("@tresjs/post-processing").ChromaticAberrationPmndrs
  'ColorAveragePmndrs': typeof import("@tresjs/post-processing").ColorAveragePmndrs
  'ColorDepthPmndrs': typeof import("@tresjs/post-processing").ColorDepthPmndrs
  'DepthOfFieldPmndrs': typeof import("@tresjs/post-processing").DepthOfFieldPmndrs
  'DepthPickingPassPmndrs': typeof import("@tresjs/post-processing").DepthPickingPassPmndrs
  'DotScreenPmndrs': typeof import("@tresjs/post-processing").DotScreenPmndrs
  'EffectComposer': typeof import("@tresjs/post-processing").EffectComposer
  'EffectComposerPmndrs': typeof import("@tresjs/post-processing").EffectComposerPmndrs
  'FXAAPmndrs': typeof import("@tresjs/post-processing").FXAAPmndrs
  'FishEyePmndrs': typeof import("@tresjs/post-processing").FishEyePmndrs
  'Glitch': typeof import("@tresjs/post-processing").Glitch
  'GlitchPmndrs': typeof import("@tresjs/post-processing").GlitchPmndrs
  'GodRaysPmndrs': typeof import("@tresjs/post-processing").GodRaysPmndrs
  'GridPmndrs': typeof import("@tresjs/post-processing").GridPmndrs
  'Halftone': typeof import("@tresjs/post-processing").Halftone
  'HueSaturationPmndrs': typeof import("@tresjs/post-processing").HueSaturationPmndrs
  'KuwaharaPmndrs': typeof import("@tresjs/post-processing").KuwaharaPmndrs
  'LensDistortionPmndrs': typeof import("@tresjs/post-processing").LensDistortionPmndrs
  'LinocutPmndrs': typeof import("@tresjs/post-processing").LinocutPmndrs
  'NoisePmndrs': typeof import("@tresjs/post-processing").NoisePmndrs
  'OutlinePmndrs': typeof import("@tresjs/post-processing").OutlinePmndrs
  'Output': typeof import("@tresjs/post-processing").Output
  'Pixelation': typeof import("@tresjs/post-processing").Pixelation
  'PixelationPmndrs': typeof import("@tresjs/post-processing").PixelationPmndrs
  'SMAA': typeof import("@tresjs/post-processing").SMAA
  'SMAAPmndrs': typeof import("@tresjs/post-processing").SMAAPmndrs
  'ScanlinePmndrs': typeof import("@tresjs/post-processing").ScanlinePmndrs
  'SepiaPmndrs': typeof import("@tresjs/post-processing").SepiaPmndrs
  'ShockWavePmndrs': typeof import("@tresjs/post-processing").ShockWavePmndrs
  'TexturePmndrs': typeof import("@tresjs/post-processing").TexturePmndrs
  'TiltShiftPmndrs': typeof import("@tresjs/post-processing").TiltShiftPmndrs
  'ToneMappingPmndrs': typeof import("@tresjs/post-processing").ToneMappingPmndrs
  'UnrealBloom': typeof import("@tresjs/post-processing").UnrealBloom
  'VignettePmndrs': typeof import("@tresjs/post-processing").VignettePmndrs
  'TresCanvas': typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue").default
  'TresCanvas': typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue").default
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyLoaderOverlay': LazyComponent<typeof import("../../src/presentation/components/ui/LoaderOverlay.vue").default>
  'LazyUIOverlay': LazyComponent<typeof import("../../src/presentation/components/ui/UIOverlay.vue").default>
  'LazyBleedingText': LazyComponent<typeof import("../../src/components/BleedingText.vue").default>
  'LazyCustomCursor': LazyComponent<typeof import("../../src/components/CustomCursor.vue").default>
  'LazyPoemMiniature': LazyComponent<typeof import("../../src/components/PoemMiniature.vue").default>
  'LazyGalleryScene': LazyComponent<typeof import("../../src/components/canvas/GalleryScene.vue").default>
  'LazyLiquidText': LazyComponent<typeof import("../../src/components/canvas/LiquidText.vue").default>
  'LazyLoadingSpiral': LazyComponent<typeof import("../../src/components/canvas/LoadingSpiral.vue").default>
  'LazyMainScene': LazyComponent<typeof import("../../src/components/canvas/MainScene.vue").default>
  'LazyPoemCard': LazyComponent<typeof import("../../src/components/canvas/PoemCard.vue").default>
  'LazyPostProcessing': LazyComponent<typeof import("../../src/components/canvas/PostProcessing.vue").default>
  'LazySineWaveMesh': LazyComponent<typeof import("../../src/components/canvas/SineWaveMesh.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyAlign': LazyComponent<typeof import("@tresjs/cientos").Align>
  'LazyAnimatedSprite': LazyComponent<typeof import("@tresjs/cientos").AnimatedSprite>
  'LazyBackdrop': LazyComponent<typeof import("@tresjs/cientos").Backdrop>
  'LazyBakeShadows': LazyComponent<typeof import("@tresjs/cientos").BakeShadows>
  'LazyBaseCameraControls': LazyComponent<typeof import("@tresjs/cientos").BaseCameraControls>
  'LazyBillboard': LazyComponent<typeof import("@tresjs/cientos").Billboard>
  'LazyBox': LazyComponent<typeof import("@tresjs/cientos").Box>
  'LazyCameraControls': LazyComponent<typeof import("@tresjs/cientos").CameraControls>
  'LazyCatmullRomCurve3': LazyComponent<typeof import("@tresjs/cientos").CatmullRomCurve3>
  'LazyCircle': LazyComponent<typeof import("@tresjs/cientos").Circle>
  'LazyCone': LazyComponent<typeof import("@tresjs/cientos").Cone>
  'LazyContactShadows': LazyComponent<typeof import("@tresjs/cientos").ContactShadows>
  'LazyCubeCamera': LazyComponent<typeof import("@tresjs/cientos").CubeCamera>
  'LazyCustomShaderMaterial': LazyComponent<typeof import("@tresjs/cientos").CustomShaderMaterial>
  'LazyCylinder': LazyComponent<typeof import("@tresjs/cientos").Cylinder>
  'LazyDodecahedron': LazyComponent<typeof import("@tresjs/cientos").Dodecahedron>
  'LazyEdges': LazyComponent<typeof import("@tresjs/cientos").Edges>
  'LazyEnvironment': LazyComponent<typeof import("@tresjs/cientos").Environment>
  'LazyFBXModel': LazyComponent<typeof import("@tresjs/cientos").FBXModel>
  'LazyFbo': LazyComponent<typeof import("@tresjs/cientos").Fbo>
  'LazyFit': LazyComponent<typeof import("@tresjs/cientos").Fit>
  'LazyGLTFModel': LazyComponent<typeof import("@tresjs/cientos").GLTFModel>
  'LazyGlobalAudio': LazyComponent<typeof import("@tresjs/cientos").GlobalAudio>
  'LazyGradientTexture': LazyComponent<typeof import("@tresjs/cientos").GradientTexture>
  'LazyGrid': LazyComponent<typeof import("@tresjs/cientos").Grid>
  'LazyHolographicMaterial': LazyComponent<typeof import("@tresjs/cientos").HolographicMaterial>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyIcosahedron': LazyComponent<typeof import("@tresjs/cientos").Icosahedron>
  'LazyImage': LazyComponent<typeof import("@tresjs/cientos").Image>
  'LazyKeyboardControls': LazyComponent<typeof import("@tresjs/cientos").KeyboardControls>
  'LazyLensflare': LazyComponent<typeof import("@tresjs/cientos").Lensflare>
  'LazyLevioso': LazyComponent<typeof import("@tresjs/cientos").Levioso>
  'LazyLightformer': LazyComponent<typeof import("@tresjs/cientos").Lightformer>
  'LazyLine2': LazyComponent<typeof import("@tresjs/cientos").Line2>
  'LazyMapControls': LazyComponent<typeof import("@tresjs/cientos").MapControls>
  'LazyMask': LazyComponent<typeof import("@tresjs/cientos").Mask>
  'LazyMeshDiscardMaterial': LazyComponent<typeof import("@tresjs/cientos").MeshDiscardMaterial>
  'LazyMeshGlassMaterial': LazyComponent<typeof import("@tresjs/cientos").MeshGlassMaterial>
  'LazyMeshReflectionMaterial': LazyComponent<typeof import("@tresjs/cientos").MeshReflectionMaterial>
  'LazyMeshWobbleMaterial': LazyComponent<typeof import("@tresjs/cientos").MeshWobbleMaterial>
  'LazyMouseParallax': LazyComponent<typeof import("@tresjs/cientos").MouseParallax>
  'LazyOcean': LazyComponent<typeof import("@tresjs/cientos").Ocean>
  'LazyOctahedron': LazyComponent<typeof import("@tresjs/cientos").Octahedron>
  'LazyOrbitControls': LazyComponent<typeof import("@tresjs/cientos").OrbitControls>
  'LazyOutline': LazyComponent<typeof import("@tresjs/cientos").Outline>
  'LazyPlane': LazyComponent<typeof import("@tresjs/cientos").Plane>
  'LazyPointerLockControls': LazyComponent<typeof import("@tresjs/cientos").PointerLockControls>
  'LazyPositionalAudio': LazyComponent<typeof import("@tresjs/cientos").PositionalAudio>
  'LazyPrecipitation': LazyComponent<typeof import("@tresjs/cientos").Precipitation>
  'LazyReflector': LazyComponent<typeof import("@tresjs/cientos").Reflector>
  'LazyRing': LazyComponent<typeof import("@tresjs/cientos").Ring>
  'LazyRoundedBox': LazyComponent<typeof import("@tresjs/cientos").RoundedBox>
  'LazySVG': LazyComponent<typeof import("@tresjs/cientos").SVG>
  'LazySampler': LazyComponent<typeof import("@tresjs/cientos").Sampler>
  'LazyScreenSizer': LazyComponent<typeof import("@tresjs/cientos").ScreenSizer>
  'LazyScreenSpace': LazyComponent<typeof import("@tresjs/cientos").ScreenSpace>
  'LazyScrollControls': LazyComponent<typeof import("@tresjs/cientos").ScrollControls>
  'LazySky': LazyComponent<typeof import("@tresjs/cientos").Sky>
  'LazySmoke': LazyComponent<typeof import("@tresjs/cientos").Smoke>
  'LazySoftShadows': LazyComponent<typeof import("@tresjs/cientos").SoftShadows>
  'LazySparkles': LazyComponent<typeof import("@tresjs/cientos").Sparkles>
  'LazySphere': LazyComponent<typeof import("@tresjs/cientos").Sphere>
  'LazyStars': LazyComponent<typeof import("@tresjs/cientos").Stars>
  'LazyStats': LazyComponent<typeof import("@tresjs/cientos").Stats>
  'LazyStatsGl': LazyComponent<typeof import("@tresjs/cientos").StatsGl>
  'LazySuperformula': LazyComponent<typeof import("@tresjs/cientos").Superformula>
  'LazyTetrahedron': LazyComponent<typeof import("@tresjs/cientos").Tetrahedron>
  'LazyText3D': LazyComponent<typeof import("@tresjs/cientos").Text3D>
  'LazyTorus': LazyComponent<typeof import("@tresjs/cientos").Torus>
  'LazyTorusKnot': LazyComponent<typeof import("@tresjs/cientos").TorusKnot>
  'LazyTransformControls': LazyComponent<typeof import("@tresjs/cientos").TransformControls>
  'LazyTube': LazyComponent<typeof import("@tresjs/cientos").Tube>
  'LazyASCIIPmndrs': LazyComponent<typeof import("@tresjs/post-processing").ASCIIPmndrs>
  'LazyBarrelBlurPmndrs': LazyComponent<typeof import("@tresjs/post-processing").BarrelBlurPmndrs>
  'LazyBloomPmndrs': LazyComponent<typeof import("@tresjs/post-processing").BloomPmndrs>
  'LazyBrightnessContrastPmndrs': LazyComponent<typeof import("@tresjs/post-processing").BrightnessContrastPmndrs>
  'LazyChromaticAberrationPmndrs': LazyComponent<typeof import("@tresjs/post-processing").ChromaticAberrationPmndrs>
  'LazyColorAveragePmndrs': LazyComponent<typeof import("@tresjs/post-processing").ColorAveragePmndrs>
  'LazyColorDepthPmndrs': LazyComponent<typeof import("@tresjs/post-processing").ColorDepthPmndrs>
  'LazyDepthOfFieldPmndrs': LazyComponent<typeof import("@tresjs/post-processing").DepthOfFieldPmndrs>
  'LazyDepthPickingPassPmndrs': LazyComponent<typeof import("@tresjs/post-processing").DepthPickingPassPmndrs>
  'LazyDotScreenPmndrs': LazyComponent<typeof import("@tresjs/post-processing").DotScreenPmndrs>
  'LazyEffectComposer': LazyComponent<typeof import("@tresjs/post-processing").EffectComposer>
  'LazyEffectComposerPmndrs': LazyComponent<typeof import("@tresjs/post-processing").EffectComposerPmndrs>
  'LazyFXAAPmndrs': LazyComponent<typeof import("@tresjs/post-processing").FXAAPmndrs>
  'LazyFishEyePmndrs': LazyComponent<typeof import("@tresjs/post-processing").FishEyePmndrs>
  'LazyGlitch': LazyComponent<typeof import("@tresjs/post-processing").Glitch>
  'LazyGlitchPmndrs': LazyComponent<typeof import("@tresjs/post-processing").GlitchPmndrs>
  'LazyGodRaysPmndrs': LazyComponent<typeof import("@tresjs/post-processing").GodRaysPmndrs>
  'LazyGridPmndrs': LazyComponent<typeof import("@tresjs/post-processing").GridPmndrs>
  'LazyHalftone': LazyComponent<typeof import("@tresjs/post-processing").Halftone>
  'LazyHueSaturationPmndrs': LazyComponent<typeof import("@tresjs/post-processing").HueSaturationPmndrs>
  'LazyKuwaharaPmndrs': LazyComponent<typeof import("@tresjs/post-processing").KuwaharaPmndrs>
  'LazyLensDistortionPmndrs': LazyComponent<typeof import("@tresjs/post-processing").LensDistortionPmndrs>
  'LazyLinocutPmndrs': LazyComponent<typeof import("@tresjs/post-processing").LinocutPmndrs>
  'LazyNoisePmndrs': LazyComponent<typeof import("@tresjs/post-processing").NoisePmndrs>
  'LazyOutlinePmndrs': LazyComponent<typeof import("@tresjs/post-processing").OutlinePmndrs>
  'LazyOutput': LazyComponent<typeof import("@tresjs/post-processing").Output>
  'LazyPixelation': LazyComponent<typeof import("@tresjs/post-processing").Pixelation>
  'LazyPixelationPmndrs': LazyComponent<typeof import("@tresjs/post-processing").PixelationPmndrs>
  'LazySMAA': LazyComponent<typeof import("@tresjs/post-processing").SMAA>
  'LazySMAAPmndrs': LazyComponent<typeof import("@tresjs/post-processing").SMAAPmndrs>
  'LazyScanlinePmndrs': LazyComponent<typeof import("@tresjs/post-processing").ScanlinePmndrs>
  'LazySepiaPmndrs': LazyComponent<typeof import("@tresjs/post-processing").SepiaPmndrs>
  'LazyShockWavePmndrs': LazyComponent<typeof import("@tresjs/post-processing").ShockWavePmndrs>
  'LazyTexturePmndrs': LazyComponent<typeof import("@tresjs/post-processing").TexturePmndrs>
  'LazyTiltShiftPmndrs': LazyComponent<typeof import("@tresjs/post-processing").TiltShiftPmndrs>
  'LazyToneMappingPmndrs': LazyComponent<typeof import("@tresjs/post-processing").ToneMappingPmndrs>
  'LazyUnrealBloom': LazyComponent<typeof import("@tresjs/post-processing").UnrealBloom>
  'LazyVignettePmndrs': LazyComponent<typeof import("@tresjs/post-processing").VignettePmndrs>
  'LazyTresCanvas': LazyComponent<typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue").default>
  'LazyTresCanvas': LazyComponent<typeof import("../../node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
